#!/usr/bin/env python3

"""ceph-tools

Usage:
    ceph-tools (cmake|clean-cmake|clean-systemd)
    ceph-tools -h|--help
"""

from pystemd.systemd1 import Manager
from shutil import rmtree
from subprocess import check_output, CalledProcessError
from typing import Union, List
from docopt import docopt
import os


def run(cmd: Union[List[str], str]) -> (str, int):
    assert type(cmd) in (list, str) and cmd
    if type(cmd) == str:
        cmd = cmd.split(' ')

    try:
        print(' '.join(cmd))
        o = check_output(cmd)
        return o.decode('utf-8'), 0
    except CalledProcessError as e:
        return e.output, e.returncode


def print_run(cmd: Union[List[str], str]) -> None:
    out, _ = run(cmd)
    if out:
        print(out)


def remove_systemd_ceph_services(keyword='ceph'):
    """
    Removes systemd services left and created by cephadm.
    """
    manager = Manager()
    manager.load()

    # fetch services
    unit_files = [
        (name.decode('utf-8'), status.decode('utf-8'))
        for name, status in manager.Manager.ListUnitFiles()
        if keyword in str(name)
    ]

    for path, status in unit_files:
        name = os.path.split(path)[-1]

        # stop
        print_run('sudo systemctl stop %s' % name)

        # disable
        print_run('sudo systemctl disable %s' % name)

        # remove
        print_run(['sudo', 'rm', path, '-rf'])

        # reload
        print_run('sudo systemctl daemon-reload')

        # remove failed
        print_run('sudo systemctl reset-failed')

    print_run('sudo rm -rf /var/lib/ceph')


def cmake():
    """
    Runs cmake with will required parameters known to work for the Dashboard.
    """
    print_run('''
        ./do_cmake.sh
            -denable_git_version=off
            -dwith_tests=on
            -dwith_ccache=on
            -dwith_radosgw_amqp_endpoint=no
            -dwith_python3=on
            -dwith_python2=off
            -dmgr_python_version=3
            -ddashboard_frontend_langs=all
            -dwith_radosgw_kafka_endpoint=off
            -dwith_mgr_dashboard_frontend=on
    ''')


if __name__ == '__main__':
    args = docopt(__doc__, version='Ceph Tools 0.1')
    if args['clean-systemd']:
        remove_systemd_ceph_services()
    elif args['cmake']:
        cmake()
    elif args['clean-cmake']:
        rmtree('./build')
        cmake()
